# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


byebye_world:
    path: /byebye-word
    controller: App\Controller\AdvertController::bye
oc_advert_index:
    path: /advert
    controller: App\Controller\AdvertController::index
oc_advert_view:
    path:   /advert/view/{id}
    controller: App\Controller\AdvertController::view
oc_advert_add:
    path:    /advert/add
    controller: App\Controller\AdvertController::add